name: Latest blog post workflow
on:
  schedule:
    # Runs every day
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          max_post_count: "3"
          feed_list: "https://dev.to/feed/jesperdramsch"
  update-readme-with-newsletter:
    name: Update this repo's README with latest activity from Newsletter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "NEWSLETTER-LIST"
          commit_message: "Updated readme with the latest Newsletter "
          max_post_count: "3"
          feed_list: "https://buttondown.email/jesper/rss"
